exp_name: 'LigandDiff'
checkpoints: models
logs: logs
n_epochs: 10
resume: 
wandb_entity: null


data: data
train_data: train
val_data: val
hidden_nf: 64
attention: True
n_layers: 2
normalization_factor: 100
normalize_factors: [1, 4, 10]

drop_rate: 0.5

diffusion_steps: 500
diffusion_noise_schedule: polynomial_2
diffusion_noise_precision: 1.0e-5
diffusion_loss_type: vlb

lr: 2.0e-4
batch_size: 2
device: gpu
model: gvp_dynamics
test_epochs: 1
normalization: batch_norm
center_of_mass: context
clip_grad: False





